# Generated by Django 6.0.3 on 2026-03-25 10:19

import cmnsd.models.BaseModel
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import locations.models.mixins.location_access_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('url_format', models.CharField(help_text='URL template with placeholders, e.g. https://waze.com/ul?ll={lat},{lon}', max_length=500)),
                ('category', models.CharField(blank=True, choices=[('navigation', 'Navigation')], max_length=50, null=True)),
                ('default_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField()),
                ('duration_s', models.FloatField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(help_text='Identifier in URL (automatically generated)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of category', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': [models.OrderBy(models.F('parent__name'), nulls_first=True), 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(help_text='Identifier in URL (automatically generated)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of location as it is identified by', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.chain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('template', models.CharField(choices=[('itinerary', 'Itinerary'), ('bucketlist', 'Bucket list'), ('themed', 'Themed list'), ('logbook', 'Logbook')], default='itinerary', max_length=20)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived lists are read-only and hidden from active views.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown is supported')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('owners_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coord_lat', models.FloatField(blank=True, null=True)),
                ('coord_lon', models.FloatField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_accommodation', models.BooleanField(default=True, editable=False)),
                ('is_activity', models.BooleanField(default=False, editable=False)),
                ('distance_to_departure_center', models.IntegerField(blank=True, help_text='Distance in km from departure center', null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='locations', to='locations.category')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.chain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(locations.models.mixins.location_access_mixin.LocationAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('stay_duration', models.PositiveSmallIntegerField(blank=True, help_text='Number of nights', null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('leg_distance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='locations.distance')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='locations.list')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='locations.location')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='list',
            name='locations',
            field=models.ManyToManyField(related_name='lists', through='locations.ListItem', to='locations.location'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='URL of the link', max_length=500)),
                ('label', models.CharField(blank=True, help_text='Optional display label for the link', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='locations.location')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='distance',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_as_destination', to='locations.location'),
        ),
        migrations.AddField(
            model_name='distance',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_as_origin', to='locations.location'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('source', models.ImageField(upload_to='images/locations/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='locations.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
                'ordering': ['visibility', '-date_modified'],
            },
        ),
        migrations.AddField(
            model_name='listitem',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='locations.media'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('slug', models.CharField(help_text='Identifier in URL (automatically generated)', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('department', 'Department'), ('locality', 'Locality')], editable=False, help_text='The level of the region based on its position in the hierarchy (automatically calculated)', max_length=10)),
                ('cached_average_distance_to_center', models.FloatField(blank=True, help_text='Average distance of all locations/subregions in this region', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parent__parent__name', 'parent__name', 'name'],
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.region'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='sizes', to='locations.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.size'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('slug', models.CharField(help_text='Identifier in URL (automatically generated)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Name of tag', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of this tag, why it is relevant')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locations', to='locations.tag'),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_maps_consent', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('apps', models.ManyToManyField(blank=True, related_name='users_with_app', to='locations.app')),
                ('family', models.ManyToManyField(blank=True, help_text='family members', related_name='family_of', to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited', to='locations.location')),
                ('hidden_locations', models.ManyToManyField(blank=True, related_name='hidden_by', to='locations.location')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_of', to='locations.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(help_text='year of visit')),
                ('month', models.PositiveIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('day', models.PositiveIntegerField(blank=True, help_text='day of visit', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visits',
                'ordering': ['location', 'year', 'month', 'day'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visited_locations', through='locations.Visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('object_id', models.PositiveBigIntegerField()),
                ('text', models.TextField(help_text='Markdown supported', verbose_name='comment text')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='comment_ct_object_idx'), models.Index(fields=['status'], name='comment_status_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('origin', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'order')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['status', 'visibility'], name='location_status_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_accommodation'], name='location_is_accommodation_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_activity'], name='location_is_activity_idx'),
        ),
    ]
