# Generated by Django 6.0.3 on 2026-03-28 19:57

import cmnsd.models.BaseModel
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userpreferences_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=cmnsd.models.BaseModel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1)),
                ('slug', models.SlugField(help_text='URL identifier, e.g. "privacy" or "about"')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands'), ('fr', 'Français')], default='en-us', help_text='Language this page is written in', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Markdown supported')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug', 'language'],
                'abstract': False,
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
