# Generated by Django 6.0.3 on 2026-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_page_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
