# Generated by Django 6.0.3 on 2026-04-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='completeness',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
