# Generated by Django 6.0.3 on 2026-04-03 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_add_location_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='end_day',
            field=models.PositiveIntegerField(blank=True, help_text='day of last day of visit', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='visits',
            name='end_month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, help_text='year of last day of visit', null=True),
        ),
    ]
