# Generated by Django 6.0.3 on 2026-04-03 19:01

from django.db import migrations, models
from locations.models.Media import media_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_visits_end_day_visits_end_month_visits_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ImageField(upload_to=media_upload_path),
        ),
    ]
