# Generated by Django 6.0.3 on 2026-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_add_media_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='recommendation',
            field=models.IntegerField(blank=True, choices=[(1, 'Recommend'), (0, 'Neutral'), (-1, 'Do not recommend')], null=True, verbose_name='recommendation'),
        ),
    ]
