# Generated by Django 6.0.3 on 2026-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_add_visits_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Comma-separated translations, auto-populated on save'),
        ),
        migrations.AddField(
            model_name='tag',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Comma-separated translations, auto-populated on save'),
        ),
    ]
