# Generated by Django 6.0.3 on 2026-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_add_aliases_to_category_and_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='similarity_weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Relative weight used in similarity scoring; increase for tags that strongly define a location (default: 100)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='c', max_length=1),
        ),
    ]
