# Generated by Django 6.0.4 on 2026-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_add_sorl_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_upcoming_visits',
            field=models.BooleanField(default=True),
        ),
    ]
